Update Makefile, timer8bit0

diff --git a/atmega328p/Makefile b/atmega328p/Makefile
--- a/atmega328p/Makefile
+++ b/atmega328p/Makefile
@@ -1,8 +1,7 @@
 GLISS = ../gliss/gep/gliss-csim
 CFLAGS = -I.. -g
 
-NMPS = \
-	portd.nmp
+NMPS = tc8bit0.nmp
 
 
 all: libatmega328p.a
@@ -18,3 +17,17 @@ libatmega328p.a: $(NMPS:.nmp=.o)
 	$(GLISS) $<
 	mv $@ $(@:.c=.h) ../ 
 	cd samples; make
+
+# Commandes pour tester la génération des composants de nml vers c et h via GLISS.
+# Les tests de génération doivent se faire directement dans le dossier atmega328p.
+# Pour nettoyer à la fin du développement, utiliser la commande dev-clean.
+
+dev:
+	@if [ -z "$(f)" ]; then \
+		echo "Error: please specify a .nmp file with f=filename.nmp"; \
+		exit 1; \
+	fi
+	$(GLISS) $(f)
+
+dev-clean:
+	-rm *.c *.h
